name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:

  deploy-to-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4.0.1
    - name: Checkout
      uses: actions/checkout@master
      
    - name: deploy
      run: npm run deploy



