name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:

  deploy-to-pages:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
    - uses: actions/setup-node@v4.0.1
    - name: npm-test
      run: |
        npm version
        echo 'good'
        pwd
        
    - name: Checkout
      uses: actions/checkout@master

    - name: pwd
      run: |
        pwd
        npm install 
      
    - name: deploy
      run: npm run deploy



